Reviews view
HabaHaba05/FromLocalsWeb pull request #20
Opened 2020-11-12 19:13 UTC by Rangatin

Reviews are now placed in scrollable panel;
Added a ...more button for bigger amount of reviews. It appears only if a service has more than 10 reviews. 
Profile image is now displayed for registered users, when they are reviewing other vendor services.

**IMPORTANT** now sender image is being saved in reviews table ONLY for registered users.  Don't know, if it was done correctly.
Please, **Review**.

2020-11-12 19:59 UTC, StauceLukas approved these changes

2020-11-12 21:22 UTC, HabaHaba05 requested changes
I'm 100% sure that we don't need to save images again.

If you don't get any ideas on how to get it working without it, write to me, I will help.
But the idea is simple, just create something like `IEnumerable<Tuple<string, byte[]>>` in ReviewViewModel, and while taking reviews from Database take image too.

2020-11-13 07:24 UTC, Rangatin commented
> I'm 100% sure that we don't need to save images again.
> 
> If you don't get any ideas on how to get it working without it, write to me, I will help.
> But the idea is simple, just create something like `IEnumerable<Tuple<string, byte[]>>` in ReviewViewModel, and while taking reviews from Database take image too.

That's is why I asked for the review. Thank you, I tried saving byte[] in ReviewViewModel and it didn't work, so somehow I understood that saving it in the database was the only other option. It turns out, it isn't.

2020-11-13 10:59 UTC, HabaHaba05 approved these changes

2020-11-13 11:11 UTC, merged